## spring server
server:
  port: 44777
  address: 0.0.0.0

## database
mybatis:
  type-aliases-package: com.simple.dao.model
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*Mapper.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.249.235:3306/simple_video_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: simplevideomysql

## redis
  redis:
    host: 120.27.249.235
    port: 6379
    password: simplevideoredis

# wechat
wechat:
  appid: wx1f9bf6eaad8130e4
  appsecret: 753b6de191053806eada02a683bc35d2

## log
logging:
  path: ./logs/
  level:
    root: info

